### ISSUE TITLE
Incompatible with EMF

### ISSUE THREAD

**Issue by IranMine123** [Salandora/SophisticatedBackpacks#71]
**Describe the bug**
Hello. it seems Backpacks mod is not compatible with [Entity Model Features (EMF)](https://github.com/Traben-0/Entity_Model_Features). the issue is I'm using a resource pack that makes player have better animation which handled by EMF. but the backpack is not get animated. here is a video:

https://github.com/user-attachments/assets/10fa9901-f18d-4910-aacb-611114c220d5

**To Reproduce**
1. Installing both Sophisticated Backpack & Core and EMF mod
2. Installing a player animation model resource pack (like [Expressive Fresh Moves](https://modrinth.com/resourcepack/tras-fresh-player))
3. doing F5 and backpack animation not synced with EMF

**Expected behavior**
Compatible with EMF, so I can see backpack is moving within the player's chest

**Versions**
Minecraft: 1.21.1 Fabric
Sophisticated Core: 0.6.50.61
Sophisticated Backpacks: 3.20.19.51
Entity Model Features (EMF): 2.2.2
Entity Texture Features (ETF): 6.2.2

**Notice**
I reported this on the official forge mod repository too. feel free to mark this as duplicate:
https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/1223

**Comment by Salandora** [comment]
I quickly checked the repositories and it seems like this is a problem between EMF and Trinket.
https://github.com/emilyploszaj/trinkets/issues/313 https://github.com/Traben-0/Entity_Model_Features/issues/216
It's also a problem with Create googles apparently. 
So for now I can't do anything.

**Comment by IranMine123** [comment]
> I quickly checked the repositories and it seems like this is a problem between EMF and Trinket. [emilyploszaj/trinkets#313](https://github.com/emilyploszaj/trinkets/issues/313) [Traben-0/Entity_Model_Features#216](https://github.com/Traben-0/Entity_Model_Features/issues/216) It's also a problem with Create googles apparently. So for now I can't do anything.

well i tried it on chestplate slot too and didnt work. @P3pp3rF1y said it should get fixed by them. so i think i should wait for @Traben-0 response.
thx

**Comment by IranMine123** [comment]
@Salandora sorry for ping but thankfully the bug gets fixed (https://github.com/P3pp3rF1y/SophisticatedBackpacks/commit/c86c72a6ff208cb9cb4c7e815495a75130c3976c).
 can you update the mod?

**Comment by Salandora** [comment]
Yeah saw that commit too. I'll work on bug fixes and introducing the new features this weekend but not sure if I have enough time to test everything and release it.

**Comment by Salandora** [comment]
New release is out, this should work better now.

**Comment by KapsiF** [comment]
Still happening with the create goggles 1.20.1 fabric 17.2, Create 0.5.1, Trinkets, 3.7.2,

**Comment by Salandora** [comment]
Like the create goggles do not work with EMF?
You would need to report that to the Create Team.

**Comment by KapsiF** [comment]
Sorry what I mean is that when the player is walking and has the goggles equipped on the trinket slot. The goggles stay stationary like for example the backpack in the video.

**Comment by Salandora** [comment]
Yeah but that is nothing I could fix here. 
This here is the repo for Sophisticated Backpacks. 
And the backpacks have been fixed for a while now.

So that's why you need to let the Create Team know about this.
